language: node_js

node_js:
    - 6

notifications:
    email: false

cache:
    directories:
        - $HOME/.npm

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8

env:
    matrix:
        - ANGULAR_VERSION=1.2.15 CXX=g++-4.8 ANGULAR_MOCKS_VERSION=1.2.18 # CXX is needed for a dependency when installing angular via node
        - ANGULAR_VERSION=1.3 ANGULAR_MOCKS_VERSION=1.3
        - ANGULAR_VERSION=1.4 ANGULAR_MOCKS_VERSION=1.4
        - ANGULAR_VERSION=1.5 ANGULAR_MOCKS_VERSION=1.4

before_script:
    # Add display needed for karma tests
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install angular@$ANGULAR_VERSION
    - npm install angular-cookies@$ANGULAR_VERSION
    - npm install angular-mocks@$ANGULAR_MOCKS_VERSION
