language: node_js

node_js:
    - 6

notifications:
    email: false

cache:
    directories:
        - $HOME/.npm

before_script:
    # Add display needed for karma tests
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
